import todoType from "../types/todoType";

const mockTodos: todoType[] = [
  {
    taskId: "1",
    userId: "abc",
    task: "Get groceries",
    description: "",
    isComplete: false,
    isChangingTask: false,
    priority: "2",
    isExpanded: false,
    tags: ["1", "3"],
    start: new Date("04/22/2025 12:12"),
    end: new Date("04/22/2025 12:12"),
    // start: null,
    // end: null,
  },
  // {
  //   id: "5",
  //   task: "Get groceries",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "2",
  //   isExpanded: false,
  //   tags: ["Food", "Entertainment"],
  //   start: new Date("04/22/2025 12:12"),
  //   end: null,
  // },
  // {
  //   id: "6",
  //   task: "Get groceries",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "2",
  //   isExpanded: false,
  //   tags: ["Food", "Entertainment"],
  //   start: new Date("04/22/2025 12:12"),
  //   end: null,
  // },
  // {
  //   id: "7",
  //   task: "Get groceries",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "2",
  //   isExpanded: false,
  //   tags: ["Food", "Entertainment"],
  //   start: new Date("04/22/2025 12:12"),
  //   end: null,
  // },
  // {
  //   id: "8",
  //   task: "Get groceries",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "2",
  //   isExpanded: false,
  //   tags: ["Food", "Entertainment"],
  //   start: new Date("04/22/2025 12:12"),
  //   end: null,
  // },
  // {
  //   id: "9",
  //   task: "Get groceries",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "2",
  //   isExpanded: false,
  //   tags: ["Food", "Entertainment"],
  //   start: new Date("04/22/2025 12:12"),
  //   end: null,
  // },
  // {
  //   id: "10",
  //   task: "Get groceries",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "2",
  //   isExpanded: false,
  //   tags: ["Food", "Entertainment"],
  //   start: new Date("04/22/2025 12:12"),
  //   end: null,
  // },
  // {
  //   id: "11",
  //   task: "Get groceries",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "2",
  //   isExpanded: false,
  //   tags: ["Food", "Entertainment"],
  //   start: new Date("04/22/2025 12:12"),
  //   end: null,
  // },
  // {
  //   id: "12",
  //   task: "Get groceries",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "2",
  //   isExpanded: false,
  //   tags: ["Food", "Entertainment"],
  //   start: new Date("04/22/2025 12:12"),
  //   end: null,
  // },
  // {
  //   taskId: "2",
  //   userId: "abc",
  //   task: "Feed cat",
  //   description: "",
  //   isComplete: false,
  //   isChangingTask: false,
  //   priority: "1",
  //   isExpanded: false,
  //   tags: ["1"],
  //   start: null,
  //   end: null,
  // },
  // {
  //   taskId: "3",
  //   userId: "abc",
  //   task: "Eat lunch",
  //   description:
  //     "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolores odit iusto eos natus, amet harum? Consectetur, veniam! Adipisci delectus, inventore, nemo at saepe soluta corrupti sed enim ratione qui molestias ab. Laboriosam vel nobis accusamus alias aut minus eius voluptatibus quasi, beatae quas, laborum expedita quos autem est ad? Nisi!",
  //   isComplete: true,
  //   isChangingTask: false,
  //   priority: "3",
  //   isExpanded: false,
  //   tags: ["1", "3"],
  //   start: null,
  //   end: null,
  // },
];

export default mockTodos;
